- name: Configure EC2 Instance for Paper.Social
  hosts: web
  become: true

  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install pip3
      yum:
        name: python3-pip
        state: present

    - name: Install docker and requests Python modules
      pip:
        name:
          - docker
          - requests
          - urllib3==1.26.16
        executable: pip3

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        published_ports:
          - 80:80

