- name: Configure EC2 Instance for Paper.Social
  hosts: all
  become: true

  vars:
    repo_url: https://github.com/ytushar24/paper-devops-task.git
    app_dir: /home/ec2-user/paper-devops-task

  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
          - git
          - python3-pip
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install required Python packages
      pip:
        name:
          - docker
          - requests
          - urllib3==1.26.16
        executable: pip3

    - name: Remove old repo if it exists
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Clone latest code from GitHub
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: master
        force: yes

    - name: Build Docker image for Paper.Social
      community.docker.docker_image:
        name: paper-social               # <— This is the image name
        source: build
        build: 
          path: /home/ec2-user/paper-devops-task/app

    - name: Stop any existing container
      community.docker.docker_container:
        name: paper-social
        state: absent
        force_kill: true

    - name: Run Paper.Social container
      community.docker.docker_container:
        name: paper-social
        image: paper-social
        state: started
        restart_policy: always
        published_ports:
          - "80:80"

