name: Deploy to EC2 with Ansible

on:
  push:
    branches:
      - master
    paths:
      - '**/index.html'
      - '**/styles.css'
      - '**/Dockerfile'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python & pip
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip

    - name: Install Ansible 9.x
      run: |
        pip3 install "ansible<10"

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/playbook.yml \
          -i "${{ secrets.EC2_HOST }}," \
          -u ${{ secrets.EC2_USER }} \
          --private-key ~/.ssh/id_rsa

